/**
 * Header emitted at the top of every generated TypeScript file.
 * Contains the @aria-manifest-hash sentinel used by `aria-build check`
 * to detect stale generated files.
 */

export function generateFileHeader(
  address: string,
  compositionHash: string,
): string {
  return `// @generated by aria-ts-plugin — do not edit manually
// @aria-source-manifest ${address}.manifest.yaml
// @aria-manifest-hash ${compositionHash}
// Run \`aria-build generate\` to regenerate this file.
`;
}
